[build]
# Use this target if none is explicitly provided
default-target = "aarch64-unknown-linux-gnu" # 64-bit ARM target for Raspbian Lite 64bit on Raspberry Pi Zero 2W
pre-build = [
  "dpkg --add-architecture $CROSS_DEB_ARCH",
  "apt-get update && apt-get install --assume-yes libasound2-dev:$CROSS_DEB_ARCH",
]
